--========================================
--////// LOT 1 \\\\\\
--========================================


DROP TABLE BANQUE CASCADE CONSTRAINT;
DROP TABLE OPERATION CASCADE CONSTRAINT;
DROP TABLE COMPTE CASCADE CONSTRAINT;
DROP TABLE TYPECOMPTE CASCADE CONSTRAINT;
DROP TABLE AUDITDECOUVERT CASCADE CONSTRAINT;

--*Création table BANQUE*
CREATE TABLE BANQUE
(
    IdBanque INTEGER,
    LibelleBanque VARCHAR(50) NOT NULL,
    CPBanque CHAR(5) NOT NULL,
    AdresseBanque VARCHAR(50) NOT NULL,
    VilleBanque VARCHAR(30) NOT NULL
);

DROP SEQUENCE SeqIdBanque;
CREATE SEQUENCE SeqIdBanque START WITH 10000 INCREMENT BY 10;
ALTER TABLE BANQUE ADD CONSTRAINT PK_IdBanque PRIMARY KEY(IdBanque);
ALTER TABLE BANQUE ADD CONSTRAINT U_LibelleBanque UNIQUE(LibelleBanque);

--*Création table AUDITDECOUVERT*
CREATE TABLE AUDITDECOUVERT
(
    IdAudit INTEGER,
    IdCompte INTEGER NOT NULL,
    LibelleCompte VARCHAR(30) NOT NULL,
    SoldeCompte NUMBER(10,2) NOT NULL,
    DecouvertAutorise NUMBER(10,2) NOT NULL,
    Depassement NUMBER(10,2) NOT NULL,
    IdDerniereOperation INTEGER NOT NULL
);

DROP SEQUENCE SeqAudit;
CREATE SEQUENCE SeqIdAudit;

--*Création table TYPECOMPTE*
CREATE TABLE TYPECOMPTE
(
    IdTypeCompte INTEGER,
    LibelleTypeCompte VARCHAR(30) NOT NULL
);

DROP SEQUENCE SeqIdTypeCompte;
CREATE SEQUENCE SeqIdTypeCompte;
ALTER TABLE TYPECOMPTE ADD CONSTRAINT PK_IdTypeCompte PRIMARY KEY(IdTypeCompte);

--*Création table OPERATION*
CREATE TABLE OPERATION
(
    IdOperation INTEGER,
    DateOperation DATE NOT NULL,
    MontantOperation NUMBER(10,2) NOT NULL
);

DROP SEQUENCE SeqIdOperation;
CREATE SEQUENCE SeqIdOperation;
ALTER TABLE OPERATION ADD CONSTRAINT PK_IdOperation PRIMARY KEY(IdOperation);

--*Création table COMPTE*
CREATE TABLE COMPTE
(
    IdCompte INTEGER,
    LibelleCompte VARCHAR(30) NOT NULL,
    SoldeCompte NUMBER(10,2) NOT NULL,
    DecouvertAutorise NUMBER(10,2) NOT NULL,
    DateOuvertureCompte DATE NOT NULL
);

DROP SEQUENCE SeqIdCompte;
CREATE SEQUENCE SeqIdCompte;
ALTER TABLE COMPTE ADD CONSTRAINT PK_IdCompte PRIMARY KEY(IdCompte);
ALTER TABLE COMPTE ADD CONSTRAINT U_LibelleCompte UNIQUE(LibelleCompte);

--*Ajout de clés étrangère dans COMPTE et OPERATION*
ALTER TABLE COMPTE ADD (IdBanque INTEGER);
ALTER TABLE COMPTE MODIFY (IdBanque INTEGER CONSTRAINT FK_IdBanque REFERENCES BANQUE(IdBanque));
ALTER TABLE COMPTE MODIFY (IdBanque NOT NULL);
ALTER TABLE COMPTE ADD (IdTypeCompte INTEGER);
ALTER TABLE COMPTE MODIFY (IdTypeCompte INTEGER CONSTRAINT FK_IdTypeCompte REFERENCES TYPECOMPTE(IdTypeCompte));
ALTER TABLE COMPTE MODIFY (IdTypeCompte NOT NULL);
ALTER TABLE OPERATION ADD (IdCompte INTEGER);
ALTER TABLE OPERATION MODIFY (IdCompte INTEGER CONSTRAINT FK_IdCompte REFERENCES COMPTE(IdCompte));
ALTER TABLE OPERATION MODIFY (IdCompte NOT NULL);